### ISSUE TITLE
 Error: "The MDX plugin should be placed before this plugin"

### ISSUE THREAD

**Issue by fuzzthink** [vitejs/vite-plugin-react-pages#145]
Getting error:
```
error when starting dev server:
Error: [vite:react-swc] The MDX plugin should be placed before this plugin
    at configResolved (file:///Users/john/dev/origami/oriapp/node_modules/@vitejs/plugin-react-swc/index.mjs:48:17)
    at file:///Users/john/dev/origami/oriapp/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:64193:28
    at Array.map (<anonymous>)
    at resolveConfig (file:///Users/john/dev/origami/oriapp/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:64193:14)
    at async _createServer (file:///Users/john/dev/origami/oriapp/node_modules/vite/dist/node/chunks/dep-7efa13d7.js:63220:20)
    at async CAC.<anonymous> (file:///Users/john/dev/origami/oriapp/node_modules/vite/dist/node/cli.js:733:24)
```

I installed the latest vite, 'vite-plugin-react-pages', react. No install of any mdx related libs.
Vite packges:
```
    "@vitejs/plugin-react-swc": "^3.0.0",
    "vite": "4.3.2",
    "vite-plugin-react-pages": "^4.1.3",
    "vite-tsconfig-paths": "^4.2.0"
```

My vite.config.ts:
```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react-swc'
import pages from 'vite-plugin-react-pages'
import { resolve, join } from 'path'

export default defineConfig({
  resolve: {
    alias: {
      '@/components': resolve(__dirname, 'src/components'),
      '@': resolve(__dirname, 'src'),
    },
  },
  plugins: [
    react(),
    pages({
      pagesDir: join(__dirname, 'src/pages'),
    }),
  ],
})
```

thank you

**Comment by csr632** [comment]
Currently you should use `@vitejs/plugin-react` instead of `@vitejs/plugin-react-swc`. I will checkout why `@vitejs/plugin-react-swc` later in this month. Thanks for your report!
